### ISSUE TITLE
issue bdist_wheel upload failes for python3

### ISSUE THREAD

**Issue by thilo-maurer** [uqfoundation/pox#15]
After
```
pip3 download pox --no-binary :all:
```
then extracting the package, then
* build good
* upload failes, when using python3 (python2 is fine)

Reason is that in this projects's `setup.py` line 234, argument `classifiers` should be an array, not a tuple. Replacing `(` by `[` fixes the issue.

See log below:
```
root@host:/build/pox-0.2.4.tar.gz.extracted/pox-0.2.4# python3 setup.py bdist_wheel upload -r artifactory
running bdist_wheel
running build
running build_py
copying pox/info.py -> build/lib/pox
running build_scripts
installing to build/bdist.linux-ppc64le/wheel
running install
running install_lib
creating build/bdist.linux-ppc64le/wheel
creating build/bdist.linux-ppc64le/wheel/pox
copying build/lib/pox/_disk.py -> build/bdist.linux-ppc64le/wheel/pox
copying build/lib/pox/__main__.py -> build/bdist.linux-ppc64le/wheel/pox
copying build/lib/pox/info.py -> build/bdist.linux-ppc64le/wheel/pox
copying build/lib/pox/utils.py -> build/bdist.linux-ppc64le/wheel/pox
creating build/bdist.linux-ppc64le/wheel/pox/tests
copying build/lib/pox/tests/__main__.py -> build/bdist.linux-ppc64le/wheel/pox/tests
copying build/lib/pox/tests/test_utils.py -> build/bdist.linux-ppc64le/wheel/pox/tests
copying build/lib/pox/tests/__init__.py -> build/bdist.linux-ppc64le/wheel/pox/tests
copying build/lib/pox/tests/test_shutils.py -> build/bdist.linux-ppc64le/wheel/pox/tests
copying build/lib/pox/__init__.py -> build/bdist.linux-ppc64le/wheel/pox
copying build/lib/pox/shutils.py -> build/bdist.linux-ppc64le/wheel/pox
running install_egg_info
running egg_info
writing pox.egg-info/PKG-INFO
writing dependency_links to pox.egg-info/dependency_links.txt
writing top-level names to pox.egg-info/top_level.txt
reading manifest file 'pox.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pox.egg-info/SOURCES.txt'
Copying pox.egg-info to build/bdist.linux-ppc64le/wheel/pox-0.2.4-py3.6.egg-info
running install_scripts
creating build/bdist.linux-ppc64le/wheel/pox-0.2.4.data
creating build/bdist.linux-ppc64le/wheel/pox-0.2.4.data/scripts
copying build/scripts-3.6/pox -> build/bdist.linux-ppc64le/wheel/pox-0.2.4.data/scripts
changing mode of build/bdist.linux-ppc64le/wheel/pox-0.2.4.data/scripts/pox to 755
creating build/bdist.linux-ppc64le/wheel/pox-0.2.4.dist-info/WHEEL
creating '/build/pox-0.2.4.tar.gz.extracted/pox-0.2.4/dist/pox-0.2.4-py3-none-any.whl' and adding '.' to it
adding 'pox/__init__.py'
adding 'pox/__main__.py'
adding 'pox/_disk.py'
adding 'pox/info.py'
adding 'pox/shutils.py'
adding 'pox/utils.py'
adding 'pox/tests/__init__.py'
adding 'pox/tests/__main__.py'
adding 'pox/tests/test_shutils.py'
adding 'pox/tests/test_utils.py'
adding 'pox-0.2.4.data/scripts/pox'
adding 'pox-0.2.4.dist-info/top_level.txt'
adding 'pox-0.2.4.dist-info/WHEEL'
adding 'pox-0.2.4.dist-info/METADATA'
adding 'pox-0.2.4.dist-info/RECORD'
removing build/bdist.linux-ppc64le/wheel
running upload
Traceback (most recent call last):
  File "setup.py", line 263, in <module>
    exec(setup_code)
  File "<string>", line 173, in <module>
  File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 131, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/distutils/command/upload.py", line 64, in run
    self.upload_file(command, pyversion, filename)
  File "/usr/local/lib/python3.6/distutils/command/upload.py", line 162, in upload_file
    body.write(value)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by mmckerns** [comment]
fixed in e0d85d7dca5e2ddc88abcfa3b44a98e813365d5d
